#!/bin/bash

# Created by: Steve Shilling
# Created Date: 11th Jan 2018

# Script to start a docker image for a student
# It requires the student name, the name of the test which should also be the docker image name and the servers Network interface

if (( $# < 3 ))
then
	echo "SYNTAX: $0 <user> <testname> <serverNIC>"
	exit 1
fi

user=$1
testcase=$2
nic=$3

# Which port to use, change these values according to your system
start_port=1030
end_port=65000
numports=7

# Do not change anything below this
assigned=0
counter=$start_port
badports=$(netstat -atn | awk '{print $4}' | sed 's/^.*://' | grep '^[0-9][0-9]*' | sort | uniq)
# useports = ssh, web, sql, amq
useports=""
ip=$(ifconfig | sed -n "/${nic}/,/Link encap/p" | grep 'inet addr' | awk '{print $2}' | sed 's/^.*://')
while (( $assigned < $numports )) && (( $counter < $end_port ))
do
	#echo -n "."
	echo "Checking port $counter"
	if echo "$badports" | grep "$counter"
	then
		continue
	fi
	if ! nc -z $ip $counter >/dev/null 2>&1
	then
		useports="$useports,$counter"
		(( assigned=assigned+1 ))
	fi
	(( counter = counter + 1 ))
done
echo ""
useports=$(echo "$useports" | sed 's/^,//')
# echo $useports
ssh=$(echo "$useports" | awk -F, '{print $1}')
web=$(echo "$useports" | awk -F, '{print $2}')
web2=$(echo "$useports" | awk -F, '{print $3}')
sql=$(echo "$useports" | awk -F, '{print $4}')
amq=$(echo "$useports" | awk -F, '{print $5}')
localsql=$(echo "$useports" | awk -F, '{print $6}')
amqadmin=$(echo "$useports" | awk -F, '{print $7}')

echo "Using the following ports;"
echo "SSHWEB = ${ssh}"
echo "WEB = ${web}"
echo "SSHSQL = ${sql}"
echo "SSHAMQ = ${amq}"
echo "VM = ${user}_${testcase}"

# Run MySQL
# docker run --name ${user}_${testcase}_mysql -p ${localsql}:3306 -p ${sql}:22 -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:5.6
docker run --name ${user}_${testcase}_mysql -p ${localsql}:3306 -p ${sql}:22 -e MYSQL_ROOT_PASSWORD=my-secret-pw -d localhost:5000/mysql
sqlcmd=$(find . -name sqlschema.sh)
sleep 10
${sqlcmd} ${localsql}

# Run ActiveMQ
docker run --name=${user}_${testcase}_activemq -d \
                -e 'ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT=true' \
                -e 'ACTIVEMQ_ADMIN_LOGIN=admin' -e 'ACTIVEMQ_ADMIN_PASSWORD=admin' \
                -e 'ACTIVEMQ_MIN_MEMORY=1024' -e  'ACTIVEMQ_MAX_MEMORY=4096' \
								-p ${amq}:22 \
								-p ${amqadmin}:8161\
								localhost:5000/activemq
#                webcenter/activemq:5.14.3

# Run the app server
docker run -itd -h ${user}.${testcase} -e APPVERSION=0.1.0 -v /var/testresults:/var/testresults --name ${user}_${testcase} -p ${web2}:8080 -p ${web}:80 -p ${ssh}:22 --link ${user}_${testcase}_mysql:mysql.server --link ${user}_${testcase}_activemq:activemq.server localhost:5000/citi/${testcase}
