#!/bin/bash

# Script to suspend the test
# Author: Steve Shilling
# 19th Jan 2018

if (( $# < 2 ))
then
  echo "SYNTAX: $0 username testname" 1>&2
  exit 1
fi

user=$1
testname=$2

docker stop $(docker ps -a  | awk '{print $NF}' | grep ${user}_${testname})
