#!/bin/bash

# Wrapper script for Web front end to stop any test
# Arguments = Username TestNumber

# Author: Steve Shilling
# Date: 9th March 2018

nicName=$(grep NICNAME tshoot.conf | awk -F':' '{print $2}')

exec ./destroy_test $1 test${2}
